# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"expand_dim_to_3": "00_csf.ipynb",
         "intensity_region_1": "00_csf.ipynb",
         "intensity_region_2": "00_csf.ipynb",
         "seperability_filter": "00_csf.ipynb",
         "CircularSeparabilityFilter": "00_csf.ipynb"}

modules = ["csf.py"]

doc_url = "https://AtomScott.github.io/circle_finder/"

git_url = "https://github.com/AtomScott/circle_finder/tree/master/"

def custom_doc_links(name): return None
