# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"expand_dim_to_3": "00_core.ipynb",
         "parametric_ellipse": "00_core.ipynb",
         "elliplise": "00_core.ipynb",
         "EllipticalSeparabilityFilter": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://AtomScott.github.io/circle_finder/"

git_url = "https://github.com/AtomScott/circle_finder/tree/master/"

def custom_doc_links(name): return None
